"""PhoneCall

Revision ID: 829af7c592dd
Revises: f03e9a1b5629
Create Date: 2023-12-20 14:13:44.395909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829af7c592dd'
down_revision = 'f03e9a1b5629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_caller', sa.String(length=20), nullable=True),
    sa.Column('number_of_receiver', sa.String(length=20), nullable=True),
    sa.Column('caller', sa.String(length=100), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_call')
    # ### end Alembic commands ###
