"""added hash

Revision ID: 886284b9921a
Revises: e376d319129c
Create Date: 2023-11-15 21:12:44.150690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886284b9921a'
down_revision = 'e376d319129c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
